services:

  django:
    build: ./django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django/:/usr/src/app/
    env_file:
      - ./.env.dev

  nginx:
    image: nginx:1.25
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/demopage:/sites/demo
    ports:
      - "80:80"
    depends_on:
      - django

