version: "3.9"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/demopage:/sites/demo
    ports:
      - "80:80"
    depends_on:
      - django

  django:
    build:
      dockerfile: Dockerfile
      context: ./django
    ports:
      - "8000:8000"
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn testing.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./django:/code